### ISSUE TITLE
启动失败，java.lang.ClassNotFoundException: org.apache.http.HttpRequest，jar包全的

### ISSUE THREAD

**Issue by wj307** [binarywang/weixin-java-miniapp-demo#11]
Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_91]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_91]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_91]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_91]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_91]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_91]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_91]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_91]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_91]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at com.github.binarywang.demo.wx.miniapp.config.WxMaConfiguration.lambda$5(WxMaConfiguration.java:116) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_91]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_91]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_91]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_91]
	at com.github.binarywang.demo.wx.miniapp.config.WxMaConfiguration.services(WxMaConfiguration.java:120) ~[classes/:na]
	at com.github.binarywang.demo.wx.miniapp.config.WxMaConfiguration$$EnhancerBySpringCGLIB$$2ab57fc4.CGLIB$services$0(<generated>) ~[classes/:na]
	at com.github.binarywang.demo.wx.miniapp.config.WxMaConfiguration$$EnhancerBySpringCGLIB$$2ab57fc4$$FastClassBySpringCGLIB$$bba5de74.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at com.github.binarywang.demo.wx.miniapp.config.WxMaConfiguration$$EnhancerBySpringCGLIB$$2ab57fc4.services(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_91]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	... 50 common frames omitted

**Comment by wj307** [comment]
![image](https://user-images.githubusercontent.com/40484511/50592914-1b457000-0ed1-11e9-88ac-119abba96d72.png)
