### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by hnulst** [binarywang/weixin-java-miniapp-demo#47]
正常测试时比较大概率出现如下堆栈，不知道是传输过来的数据解密失败还是为啥

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.6.jar!/:na]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar!/:na]
at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar!/:na]
at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar!/:na]
at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar!/:na]
at cn.binarywang.wx.miniapp.bean.WxMaPhoneNumberInfo.fromJson(WxMaPhoneNumberInfo.java:23) ~[weixin-java-miniapp-4.1.0.jar!/:na]
at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getPhoneNoInfo(WxMaUserServiceImpl.java:58) ~[weixin-java-miniapp-4.1.0.jar!/:na]
....

**Comment by binarywang** [comment]
参考wxjava wiki里的常见问题
