### ISSUE TITLE
k8s里面部署微信小程序后，登录报错

### ISSUE THREAD

**Issue by yfgcq** [binarywang/weixin-java-miniapp-demo#77]
`
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-miniapp</artifactId>
    <version>4.3.0</version>
</dependency>

 ERROR com.xxx.handle.GlobalException  42   
 - me.chanjar.weixin.common.error.WxRuntimeException: java.net.UnknownHostException: api.weixin.qq.com: Temporary failure in name resolution
        at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.getAccessToken(BaseWxMaServiceImpl.java:175)
        at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.executeInternal(BaseWxMaServiceImpl.java:261)
        at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.execute(BaseWxMaServiceImpl.java:224)
        at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.post(BaseWxMaServiceImpl.java:198)
        at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getNewPhoneNoInfo(WxMaUserServiceImpl.java:68)
`

**Comment by binarywang** [comment]
这报错明显是你的网络问题吧，检查下为啥解析不了域名
